// 04-insert-component/vue-prompt-component/src/components/LoginForm.vue
<script setup>
const handleSubmit = () => {
  alert("Login form submitted")
}
</script>
<template>
  <form @submit.prevent="handleSubmit">
    <input type="email" placeholder="Email" />
    <input type="password" placeholder="Password" />
    <button type="submit">Login</button>
  </form>
</template>
<style></style>

// 04-insert-component/react-prompt-component/src/components/LoginForm.jsx
const LoginForm = () => {
  return (
    <form>
      <div className="form-group">
        <label htmlFor="username">Username</label>
        <input type="text" id="username" className="form-control" />
      </div>
      <div className="form-group">
        <label htmlFor="password">Password</label>
        <input type="password" id="password" className="form-control" />
      </div>
      <button type="submit" className="btn btn-primary">
        Login
      </button>
    </form>
  )
}

export default LoginForm
