// 04-insert-component/vue-prompt-component/src/components/RecommendProducts.vue
<script setup></script>
<template>
  <div
    class="flex rounded-lg ring-1 ring-gray-300 overflow-hidden shadow-md my-4"
  >
    <img
      class="w-[150px] h-[150px] object-cover block"
      width="300"
      height="200"
      src="https://picsum.photos/seed/picsum/300/200"
      alt="fake img"
    />
    <div class="flex flex-col flex-grow">
      <div class="p-4 flex-grow">
        <div class="flex justify-between mb-2">
          <div>Product</div>
          <div>$300</div>
        </div>

        <div class="text-gray-400">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse iste
          voluptate architecto ab, quae natus nam quod consequatur illo.
          Asperiores quam consectetur iusto nam eum enim reprehenderit
          voluptatem assumenda quibusdam?
        </div>
      </div>
      <!-- <div class="flex py-2 px-4 gap-2"></div> -->
    </div>
  </div>
</template>
<style></style>

// 04-insert-component/react-prompt-component/src/components/RecommendProducts.jsx
const RecommendProducts = () => {
  return (
    <div className="flex rounded-lg ring-1 ring-gray-300 overflow-hidden shadow-md my-4">
      <img
        className="w-[150px] h-[150px] object-cover block"
        width="300"
        height="200"
        src="https://picsum.photos/seed/picsum/300/200"
        alt="fake img"
      />
      <div className="flex flex-col flex-grow">
        <div className="p-4 flex-grow">
          <div className="flex justify-between mb-2">
            <div>Product</div>
            <div>$300</div>
          </div>

          <div className="text-gray-400">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse iste
            voluptate architecto ab, quae natus nam quod consequatur illo.
            Asperiores quam consectetur iusto nam eum enim reprehenderit
            voluptatem assumenda quibusdam?
          </div>
        </div>
      </div>
    </div>
  )
}

export default RecommendProducts
